services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    command: [
      "--max_connections=1000",
      "--innodb_buffer_pool_size=1G",
      "--innodb_log_file_size=256M"
    ]
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - frappe-network
  
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    networks:
      - frappe-network
  
  frappe:
    image: frappe/frappe-worker:v14.32.0
    container_name: frappe
    depends_on:
      - mariadb
      - redis
    environment:
      SITE_NAME: ${SITE_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      DEVELOPER_MODE: ${DEVELOPER_MODE}
      MARIADB_HOST: mariadb
      FRAPPE_VERSION: v15.7.1
    ports:
      - "8000:8000"
    volumes:
      - frappe_sites:/home/frappe/frappe-bench/sites
      - frappe_assets:/home/frappe/frappe-bench/sites/assets
    restart: always
    networks:
      - frappe-network
    
    
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    depends_on:
      - frappe
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - frappe-network

  acme:
    image: nginxproxy/acme-companion
    container_name: acme
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      - frappe-network


volumes:
  mariadb_data:
  frappe_sites:
  frappe_assets:
  certs:
  vhost:
  html:

networks:
  frappe-network:
    driver: bridge
