services:
  postgres:
    image: postgres:15
    container_name: postgres
    command: [
      "-c", "max_connections=100",
      "-c", "shared_buffers=128 MB",
      ]
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - frappe-network
  
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    networks:
      - frappe-network
  
  frappe:
    image: frappe/frappe-worker:latest
    container_name: frappe
    depends_on:
      - postgres
      - redis
    environment:
      SITE_NAME: ${SITE_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      DEVELOPER_MODE: ${DEVELOPER_MODE}
    ports:
      - "8000:8000"
    volumes:
      - frappe_sites:/home/frappe/frappe-bench/sites
      - frappe_assets:/home/frappe/frappe-bench/sites/assets
    restart: always
    networks:
      - frappe-network
    
    
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    depends_on:
      - frappe
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - frappe-network

  acme:
    image: nginxproxy/acme-companion
    container_name: acme
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      - frappe-network


volumes:
  postgres_data:
  frappe_sites:
  frappe_assets:
  certs:
  vhost:
  html:

networks:
  frappe-network:
    driver: bridge
