sservices:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - frappe-network
  
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    networks:
      - frappe-network
  
  frappe:
    image: frappe/frappe-worker:${FRAPPE_VERSION}
    container_name: frappe
    depends_on:
      - mariadb
      - redis
    environment:
      SITE_NAME: ${SITE_NAME}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      DEVELOPER_MODE: ${DEVELOPER_MODE}
      MARIADB_HOST: ${DB_HOST}
    ports:
      - "8000:8000"
    volumes:
      - frappe_sites:/home/frappe/frappe-bench/sites
      - frappe_assets:/home/frappe/frappe-bench/sites/assets
    restart: always
    networks:
      - frappe-network
    command: >
      bash -c "
      until nc -z mariadb 3306; do sleep 1; done &&
      until nc -z redis 6379; do sleep 1; done &&
      cd /home/frappe/frappe-bench &&
      [ ! -f /home/frappe/frappe-bench/sites/${SITE_NAME}/site_config.json ] &&
      bench new-site ${SITE_NAME} --db-name ${DB_NAME} --db-password ${DB_PASSWORD} --admin-password ${ADMIN_PASSWORD} --install-app erpnext || true &&
      bench --site ${SITE_NAME} set-config hostname ${VIRTUAL_HOST} &&
      bench --site ${SITE_NAME} set-config enable_ssl_certificate 1 &&
      bench --site ${SITE_NAME} enable-scheduler &&
      bench start
      "
    
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    depends_on:
      - frappe
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - frappe-network

  acme:
    image: nginxproxy/acme-companion
    container_name: acme
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      - frappe-network

volumes:
  mariadb_data:
  frappe_sites:
  frappe_assets:
  certs:
  vhost:
  html:

networks:
  frappe-network:
    driver: bridge